Update condition
ClaimReviewParser.parsers already returns only enabled parsers:

  def self.parsers
    QuietHashie[
      Hash[ClaimReviewParser.enabled_subclasses.map do |sc|
        [sc.service, sc]
      end]
    ]
  end

ClaimReviewParser.parsers
=> #<QuietHashie reuters_brazil=ReutersBrazil reuters_spanish=ReutersSpanish>

irb(main):003:0> ClaimReviewParser.parsers['aos_fatos']
=> nil

This causes
"\"error_message\":\"undefined method `deprecated' for nil:NilClass\",
\"error_class\":\"NoMethodError\",\"failed_at\":1761238248.0907707,
\"retry_count\":6,\"retried_at\":1761239681.7711115}"}"