Update requeueing condition to avoid no method error (#415)
ClaimReviewParser.parsers already returns only enabled parsers. So when we try `!ClaimReviewParser.parsers[service].deprecated` with a deprecated service, it returns nil.

Which causes:
"\"error_message\":\"undefined method `deprecated' for nil:NilClass\",
\"error_class\":\"NoMethodError\",\"failed_at\":1761238248.0907707,
\"retry_count\":6,\"retried_at\":1761239681.7711115}"}"