CV2-6609 - Update article-body__content to article-body-module__content (#417)
We seem to be getting: `undefined method search' for nil:NilClass:00:00`. 
Reviewing both portuguese and spanish pages, it looks like the class `article-body__content` is now `article-body-module__content`.

References: CV2-6609

I was able to reproduce the error by mismatching the classname:

```
  1) Reuters instance parses a raw_claim_review
     Failure/Error: header = page.search('div[class^="article-body-module__content"]').first.search('h2[data-testid="Heading"]').last

     NoMethodError:
       undefined method `search' for nil:NilClass
     # ./lib/claim_review_parsers/reuters.rb:44:in `claim_result_from_subhead'
     # ./lib/claim_review_parsers/reuters.rb:51:in `claim_result_from_page'
     # ./lib/claim_review_parsers/reuters.rb:59:in `parse_raw_claim_review'
     # ./spec/lib/claim_review_parsers/reuters_test.rb:20:in `block (3 levels) in <top (required)>'
     # /usr/local/bundle/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'
```